#!/usr/bin/env php
<?php
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}
define('PHPUNIT_COMPOSER_INSTALL', __DIR__. '/../vendor/autoload.php');
require PHPUNIT_COMPOSER_INSTALL;
PHPUnit_TextUI_Command::main();
